services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wppack_test
    ports:
      - '3306:3306'
    tmpfs:
      - /var/lib/mysql
  valkey:
    image: valkey/valkey:8
    ports:
      - '6379:6379'
    tmpfs:
      - /data
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - '8000:8000'
    tmpfs:
      - /home/dynamodblocal/data
  memcached:
    image: memcached:1.6
    ports:
      - '11211:11211'
