<?php

/*
 * This file is part of the WPPack package.
 *
 * (c) Tsuyoshi Tsurushima
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace WPPack\Component\Database\Bridge\AuroraDSQL\Translator;

use WPPack\Component\Database\Bridge\PostgreSQL\Translator\PostgreSQLQueryTranslator;
use WPPack\Component\Database\Exception\UnsupportedFeatureException;
use WPPack\Component\Database\Translator\QueryTranslatorInterface;

/**
 * Query translator for Aurora DSQL.
 *
 * The translator is MySQL-first: the user's intent comes from MySQL / wpdb
 * idioms, and DSQL's PostgreSQL subset is the target. Idioms that are common
 * in MySQL schemas but unavailable on DSQL are silently degraded so ordinary
 * WordPress / plugin DDL keeps flowing. Only DDL that expresses an intent
 * DSQL cannot fulfil (temporary tables, user-defined triggers / functions,
 * destructive ALTER TABLE) raises an UnsupportedFeatureException.
 *
 * Silent rewrites (MySQL idiom → DSQL equivalent):
 *
 * - TRUNCATE TABLE → DELETE FROM + sequence reset (DSQL: no TRUNCATE)
 * - CREATE [UNIQUE] INDEX → CREATE [UNIQUE] INDEX ASYNC (DSQL: async-only)
 * - SERIAL / BIGSERIAL / SMALLSERIAL → GENERATED BY DEFAULT AS IDENTITY
 * - FOREIGN KEY / REFERENCES in CREATE TABLE → constraint dropped (the
 *   PostgreSQL translator already ignores the REFERENCES clause and hoists
 *   FOREIGN KEY entries into plain CREATE INDEX statements; we accept that
 *   degradation — MySQL's MyISAM silently ignores FKs too)
 * - ON UPDATE CURRENT_TIMESTAMP → DEFAULT CURRENT_TIMESTAMP only; the
 *   CREATE FUNCTION + CREATE TRIGGER pair the PostgreSQL translator emits
 *   for the auto-update behaviour is filtered out on DSQL. Applications
 *   that need an updated_at column must set it explicitly on UPDATE
 *
 * Hard rejections (user wrote something DSQL cannot run; silent fallback
 * would produce a surprise rather than a translation):
 *
 * - CREATE TEMPORARY TABLE
 * - CREATE TRIGGER (user-written, as opposed to the PG translator artifact)
 * - CREATE FUNCTION / CREATE PROCEDURE
 * - ALTER TABLE DROP COLUMN
 * - ALTER TABLE ALTER COLUMN (SET DATA TYPE / SET DEFAULT / DROP DEFAULT /
 *   SET NOT NULL / DROP NOT NULL)
 * - ALTER TABLE MODIFY/CHANGE COLUMN (MySQL syntax — same outcome as
 *   ALTER COLUMN on the PG side, same rejection here)
 *
 * AWS DSQL references:
 *
 * @see https://docs.aws.amazon.com/aurora-dsql/latest/userguide/working-with-postgresql-compatibility.html
 * @see https://docs.aws.amazon.com/aurora-dsql/latest/userguide/working-with-postgresql-compatibility-sql-support.html
 * @see https://docs.aws.amazon.com/aurora-dsql/latest/userguide/working-with-postgresql-compatibility-unsupported-features.html
 */
final class AuroraDSQLQueryTranslator implements QueryTranslatorInterface
{
    private const DOC_UNSUPPORTED_URL = 'https://docs.aws.amazon.com/aurora-dsql/latest/userguide/working-with-postgresql-compatibility-unsupported-features.html';

    /**
     * Shared guidance for DROP COLUMN / ALTER COLUMN / MODIFY / CHANGE
     * rejections: DSQL has no in-place column mutation, so the migration path
     * is rename → CREATE TABLE with the new shape → full data copy → drop
     * the old table. This has to happen in the application layer because it
     * crosses multiple statements (and needs to be run outside any single
     * DDL transaction — DSQL disallows mixing DDL with DML in one tx).
     */
    private const COLUMN_MUTATION_GUIDANCE = 'Aurora DSQL does not support in-place column changes or drops. '
        . 'Migrate by renaming the existing table, creating a new table with the desired shape, '
        . 'copying rows with INSERT ... SELECT, then dropping the old table.';

    private readonly PostgreSQLQueryTranslator $pgsql;

    public function __construct()
    {
        $this->pgsql = new PostgreSQLQueryTranslator();
    }

    public function translate(string $sql): array
    {
        $this->rejectUnsupportedInput($sql);

        // TRUNCATE → DELETE FROM + sequence reset (DSQL does not support TRUNCATE).
        // MySQL TRUNCATE resets AUTO_INCREMENT. We replicate this by resetting
        // the SERIAL sequence after DELETE FROM.
        //
        // The captured table name is constrained to a SQL identifier
        // ([A-Za-z_][A-Za-z0-9_]{0,62}) — PostgreSQL's NAMEDATALEN default is
        // 64 bytes, so 63 chars after the leading letter covers the full legal
        // range. Anything outside that shape (embedded quotes, semicolons,
        // whitespace, utf-8) falls through to the PostgreSQL translator, which
        // will raise a clear error instead of silently splicing attacker-
        // controlled bytes into the generated SQL. This is defense in depth:
        // identifiers reach prepare() via WPDB tables in practice, but the
        // strict allowlist means a compromised callsite can't escalate.
        if (preg_match('/^\s*TRUNCATE\s+(?:TABLE\s+)?(?:[`"])?([A-Za-z_][A-Za-z0-9_]{0,62})(?:[`"])?\s*;?\s*$/i', trim($sql), $m)) {
            $table = $m[1];
            $quotedTable = '"' . $table . '"';
            $tableLiteral = "'" . $table . "'";

            return [
                'DELETE FROM ' . $quotedTable,
                // Reset SERIAL sequences to 1 (MySQL TRUNCATE resets AUTO_INCREMENT)
                \sprintf(
                    'SELECT setval(pg_get_serial_sequence(%s, column_name), 1, false) '
                    . 'FROM information_schema.columns '
                    . 'WHERE table_schema = current_schema() AND table_name = %s '
                    . "AND column_default LIKE 'nextval%%'",
                    $tableLiteral,
                    $tableLiteral,
                ),
            ];
        }

        $out = [];
        foreach ($this->pgsql->translate($sql) as $statement) {
            $rewritten = $this->rewriteForDsql($statement);
            if ($rewritten !== null) {
                $out[] = $rewritten;
            }
        }

        return $out;
    }

    /**
     * Reject DSQL-unsupported DDL before delegating to the PostgreSQL translator.
     *
     * These shapes have no safe rewrite: DSQL simply rejects them at runtime
     * with opaque errors, so we surface a clear UnsupportedFeatureException
     * instead of letting the query reach the server.
     */
    private function rejectUnsupportedInput(string $sql): void
    {
        $norm = ltrim($sql);

        if (preg_match('/^\s*CREATE\s+(?:LOCAL\s+|GLOBAL\s+)?TEMP(?:ORARY)?\s+TABLE\b/i', $norm)) {
            throw $this->unsupported(
                $sql,
                'Aurora DSQL does not support CREATE TEMPORARY TABLE.',
            );
        }

        if (preg_match('/^\s*CREATE\s+(?:OR\s+REPLACE\s+)?(?:CONSTRAINT\s+)?TRIGGER\b/i', $norm)) {
            throw $this->unsupported(
                $sql,
                'Aurora DSQL does not support triggers.',
            );
        }

        if (preg_match('/^\s*CREATE\s+(?:OR\s+REPLACE\s+)?(?:FUNCTION|PROCEDURE)\b/i', $norm)) {
            throw $this->unsupported(
                $sql,
                'Aurora DSQL does not support user-defined functions or procedures.',
            );
        }

        // ALTER TABLE … DROP COLUMN
        if (preg_match('/^\s*ALTER\s+TABLE\s+\S+.*\bDROP\s+COLUMN\b/is', $norm)) {
            throw $this->unsupported($sql, self::COLUMN_MUTATION_GUIDANCE);
        }

        // ALTER TABLE … MODIFY / CHANGE COLUMN (MySQL; PG translator rewrites into
        // ALTER COLUMN TYPE which DSQL also rejects — fail fast with MySQL syntax).
        if (preg_match('/^\s*ALTER\s+TABLE\s+\S+.*\b(?:MODIFY|CHANGE)\s+COLUMN\b/is', $norm)) {
            throw $this->unsupported($sql, self::COLUMN_MUTATION_GUIDANCE);
        }

        // ALTER TABLE … ALTER [COLUMN] … (SET DATA TYPE | TYPE | SET DEFAULT | DROP DEFAULT | SET NOT NULL | DROP NOT NULL)
        if (preg_match('/^\s*ALTER\s+TABLE\s+\S+.*\bALTER(?:\s+COLUMN)?\s+\S+\s+(?:SET\s+DATA\s+TYPE|TYPE|SET\s+DEFAULT|DROP\s+DEFAULT|SET\s+NOT\s+NULL|DROP\s+NOT\s+NULL)\b/is', $norm)) {
            throw $this->unsupported($sql, self::COLUMN_MUTATION_GUIDANCE);
        }
    }

    /**
     * Apply DSQL-specific rewrites to a statement produced by the PostgreSQL translator.
     *
     * Returns null to drop the statement from the output.
     */
    private function rewriteForDsql(string $sql): ?string
    {
        // The PostgreSQL translator emits CREATE OR REPLACE FUNCTION + CREATE
        // TRIGGER pairs for MySQL "ON UPDATE CURRENT_TIMESTAMP" columns. DSQL
        // has neither triggers nor PL/pgSQL, but the column's DEFAULT
        // CURRENT_TIMESTAMP is still useful on INSERT. Silently drop the
        // trigger artifact and let the CREATE TABLE proceed — the
        // auto-update behaviour on UPDATE becomes application-layer
        // responsibility, which matches how most WordPress schemas already
        // manage updated_at columns.
        //
        // User-written CREATE TRIGGER / FUNCTION / PROCEDURE statements
        // never reach this point; rejectUnsupportedInput() intercepts them.
        if (preg_match('/^\s*CREATE\s+(?:OR\s+REPLACE\s+)?(?:FUNCTION|TRIGGER)\b/i', $sql)) {
            return null;
        }

        // SERIAL family → GENERATED BY DEFAULT AS IDENTITY.
        // Order matters: match the longer variants first. Word boundaries
        // protect against partial matches inside other identifiers.
        $sql = (string) preg_replace('/\bBIGSERIAL\b/i', 'BIGINT GENERATED BY DEFAULT AS IDENTITY', $sql);
        $sql = (string) preg_replace('/\bSMALLSERIAL\b/i', 'SMALLINT GENERATED BY DEFAULT AS IDENTITY', $sql);
        $sql = (string) preg_replace('/\bSERIAL\b/i', 'INTEGER GENERATED BY DEFAULT AS IDENTITY', $sql);

        // CREATE [UNIQUE] INDEX → CREATE [UNIQUE] INDEX ASYNC.
        // DSQL requires the ASYNC keyword; synchronous index creation is not
        // supported. The keyword goes immediately after INDEX and before
        // IF NOT EXISTS / the index name.
        if (preg_match('/^\s*CREATE\s+(?:UNIQUE\s+)?INDEX\b/i', $sql)
            && !preg_match('/^\s*CREATE\s+(?:UNIQUE\s+)?INDEX\s+ASYNC\b/i', $sql)) {
            $sql = (string) preg_replace(
                '/^(\s*CREATE\s+(?:UNIQUE\s+)?INDEX)\s+/i',
                '$1 ASYNC ',
                $sql,
                1,
            );
        }

        return $sql;
    }

    private function unsupported(string $sql, string $reason): UnsupportedFeatureException
    {
        return new UnsupportedFeatureException(
            $sql,
            'dsql',
            [$reason . ' See ' . self::DOC_UNSUPPORTED_URL],
        );
    }
}
