<?php

/*
 * This file is part of the WPPack package.
 *
 * (c) Tsuyoshi Tsurushima
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace WPPack\Component\Database\Placeholder;

/**
 * Per-request storage mapping a deterministic id to the params array of a single
 * wpdb::prepare() call. WPPackWpdb uses this to keep values out of the returned
 * SQL string while still delivering them to the driver at query() execution time
 * as native prepared-statement parameters.
 *
 * id format: 16 lowercase hex characters derived from sha1($sql . "\x01" . serialize($params)).
 * Marker format: "/*WPP:<id>*\/" (SQL block comment, ignored by every engine).
 *
 * The 16-hex (64-bit) truncation puts the birthday-collision threshold at
 * roughly 2^32 distinct prepare() calls per process. A long-running WP-CLI
 * worker doing millions of prepares per hour still sits far below that, so
 * the dedup-friendly deterministic id keeps working without risking that
 * two different (sql, params) pairs ever end up sharing an entry.
 */
final class PreparedBank
{
    private const MARKER_PREFIX = '/*WPP:';
    private const MARKER_SUFFIX = '*/';
    public const MARKER_PATTERN = '#/\*WPP:([a-f0-9]{16})\*/#';

    /** @var array<string, list<mixed>> id → params */
    private array $entries = [];

    /**
     * Per-instance random salt mixed into every id. Two properties fall out:
     *   - Markers generated by this instance are unforgeable by anyone who
     *     doesn't have the salt. A hostile user string that happens to
     *     contain `/*WPP:deadbeefdeadbeef*\/` will almost never collide with
     *     a real entry, which is safer than relying on (sql, params) hash
     *     space alone.
     *   - Markers don't carry across WPPackWpdb instances. If two requests
     *     somehow share state (long-running worker, stale cache) one can't
     *     splice another's params into its own SQL.
     */
    private readonly string $salt;

    public function __construct(?string $salt = null)
    {
        $this->salt = $salt ?? bin2hex(random_bytes(8));
    }

    /**
     * Compute the deterministic id for the given (sql, params) pair.
     *
     * @param list<mixed> $params
     */
    public function idFor(string $sql, array $params): string
    {
        return substr(sha1($this->salt . "\x01" . $sql . "\x01" . serialize($params)), 0, 16);
    }

    /**
     * Build the SQL comment marker for the given id.
     */
    public function markerFor(string $id): string
    {
        return self::MARKER_PREFIX . $id . self::MARKER_SUFFIX;
    }

    /**
     * Store params under the given id. Repeated calls with the same id overwrite
     * with identical values (the id is derived from sql+params so entries are
     * idempotent).
     *
     * @param list<mixed> $params
     */
    public function store(string $id, array $params): void
    {
        $this->entries[$id] = $params;
    }

    /**
     * Extract and remove the params for all markers present in the given SQL,
     * in the order they appear. Unknown ids are silently skipped.
     *
     * @return array{0: string, 1: list<mixed>} [sqlWithMarkersRemoved, flattenedParams]
     */
    public function consume(string $sql): array
    {
        if (!str_contains($sql, self::MARKER_PREFIX)) {
            return [$sql, []];
        }

        $params = [];

        if (preg_match_all(self::MARKER_PATTERN, $sql, $matches) > 0) {
            foreach ($matches[1] as $id) {
                if (isset($this->entries[$id])) {
                    foreach ($this->entries[$id] as $value) {
                        $params[] = $value;
                    }

                    unset($this->entries[$id]);
                }
            }
        }

        $cleanSql = (string) preg_replace(self::MARKER_PATTERN, '', $sql);

        return [$cleanSql, $params];
    }

    /**
     * Drop all remaining entries (orphans from prepare() calls that were never
     * followed by a query()). Called from WPPackWpdb::resetPreparedBank().
     */
    public function reset(): void
    {
        $this->entries = [];
    }

    /**
     * For unit tests / debug.
     */
    public function size(): int
    {
        return \count($this->entries);
    }
}
